- name: Edge compute management
  hosts: "{{ target|default('all') }}"
  become: true

  pre_tasks:
    - name: Install Amazon EFS utils
      when:
        - ansible_system_vendor == "Amazon EC2"
      block:
        - name: Include amazon-efs-utils
          ansible.builtin.include_tasks: tasks/amazon-efs-utils.yml

  roles:
    - role: microk8s

  tasks: []
