- name: Edge compute management
  hosts: "{{ target|default('all') }}"
  become: true

  pre_tasks:
    - block:
      - name: amazon-efs-utils
        ansible.builtin.include_tasks: tasks/amazon-efs-utils.yml
      when:
        - ansible_system_vendor == "Amazon EC2"

  roles:
    - role: microk8s

  tasks: []
