- name: Edge compute management
  hosts: "{{ target|default('all') }}"
  become: true

  pre_tasks:
    - block:
      - name: amazon-efs-utils
        ansible.builtin.include_tasks: tasks/amazon-efs-utils.yml
      when:
        - ansible_system_vendor == "Amazon EC2"

  roles:
    - role: microk8s

  tasks:
    - block:
      - name: ingress service
        ansible.builtin.shell:
          cmd: |
            cat <<EOT |microk8s kubectl apply -f -
              apiVersion: v1
              kind: Service
              metadata:
                name: ingress
                namespace: ingress
              spec:
                selector:
                  name: nginx-ingress-microk8s
                type: LoadBalancer
                ports:
                - name: http
                  protocol: TCP
                  port: 80
                  targetPort: 80
                - name: https
                  protocol: TCP
                  port: 443
                  targetPort: 443
            EOT

      - name: ingress IP via LB
        ansible.builtin.shell:
          cmd: |
            microk8s kubectl -ningress get daemonset nginx-ingress-microk8s-controller -o yaml \
            |sed -e 's|- --publish-status-address=.*|- --publish-service=$(POD_NAMESPACE)/ingress|' \
            |microk8s kubectl apply -f -
      tags: [never,ingress]
