- name: microk8s development environment
  hosts: "{{ target|default('all') }}"
  become: true

  roles:
    - microk8s
    - role: named
      when: named_enabled

  tasks:
    - block:
      - name: amazon-efs-utils
        ansible.builtin.include_tasks: tasks/amazon-efs-utils.yml
      when:
        - ansible_system_vendor == "Amazon EC2"

    - block:
      - name: /usr/local/bin/finalise-external-dns.sh
        ansible.builtin.template:
          dest: /usr/local/bin/finalise-external-dns.sh
          lstrip_blocks: true
          mode: "0755"
          src: templates/usr/local/bin/finalise-external-dns.sh.j2

      - block:
        - name: /etc/resolv.conf is symlink?
          ansible.builtin.stat:
            path: /etc/resolv.conf
          register: resolv_conf

        - block:
          - name: unlink /etc/resolv.conf from systemd-resolved
            ansible.builtin.command:
              cmd: unlink /etc/resolv.conf

          - name: copy /run/systemd/resolve/stub-resolv.conf to /etc/resolv.conf
            ansible.builtin.shell:
              cmd: sed -n -e '/^#/!p' /run/systemd/resolve/stub-resolv.conf >/etc/resolv.conf
          when: resolv_conf.stat.islnk

        - name: set nameserver
          ansible.builtin.lineinfile:
            line: nameserver {{ ansible_default_ipv4.address }}
            path: /etc/resolv.conf
            search_string: nameserver

        - name: microk8s set nameserver
          ansible.builtin.shell:
            cmd: >
              microk8s kubectl -n kube-system get configmap/coredns -oyaml
              | sed 's/forward \. .*$/forward . {{ ansible_default_ipv4.address }}/'
              | microk8s kubectl apply -f -
        tags: [bind,named,resolvd]
      when:
        - named_enabled

    - block:
      - name: ingress service
        ansible.builtin.shell:
          cmd: |
            cat <<EOT |microk8s kubectl apply -f -
              apiVersion: v1
              kind: Service
              metadata:
                name: ingress
                namespace: ingress
              spec:
                selector:
                  name: nginx-ingress-microk8s
                type: LoadBalancer
                ports:
                - name: http
                  protocol: TCP
                  port: 80
                  targetPort: 80
                - name: https
                  protocol: TCP
                  port: 443
                  targetPort: 443
            EOT

      - name: ingress IP via LB
        ansible.builtin.shell:
          cmd: |
            microk8s kubectl -ningress get daemonset nginx-ingress-microk8s-controller -o yaml \
            |sed -e 's|- --publish-status-address=.*|- --publish-service=$(POD_NAMESPACE)/ingress|' \
            |microk8s kubectl apply -f -
      tags: [ingress]
