- name: microk8s development environment
  hosts: localhost
  become: true
  connection: local

  roles:
    - microk8s
    - named

  tasks:
    - block:
      - name: /etc/resolv.conf is symlink?
        ansible.builtin.stat:
          path: /etc/resolv.conf
        register: resolv_conf

      - block:
        - name: unlink /etc/resolv.conf from systemd-resolved
          ansible.builtin.command:
            cmd: unlink /etc/resolv.conf

        - name: copy /run/systemd/resolve/stub-resolv.conf to /etc/resolv.conf
          ansible.builtin.shell:
            cmd: sed -n -e '/^#/!p' /run/systemd/resolve/stub-resolv.conf >/etc/resolv.conf
        when: resolv_conf.stat.islnk

      - name: set nameserver
        ansible.builtin.lineinfile:
          line: nameserver {{ ansible_default_ipv4.address }}
          path: /etc/resolv.conf
          search_string: nameserver

      - name: microk8s set nameserver
        ansible.builtin.shell:
          cmd: >
            microk8s kubectl -n kube-system get configmap/coredns -oyaml
            | sed 's/forward \. .*$/forward . {{ ansible_default_ipv4.address }}/'
            | microk8s kubectl apply -f -
      tags: [bind,named,resolvd]
