# https://www.gnu.org/software/wget/manual/html_node/Proxies.html
- name: Configure http_proxy
  ansible.builtin.blockinfile:
    block: |
      http_proxy={{ http_proxy }}
      https_proxy={{ https_proxy|default http_proxy }}
      ftp_proxy={{ ftp_proxy|default http_proxy }}
      no_proxy=localhost,.local,.svc,127.0.0.1,::1
      {{- ',%s'|format(ansible_hostname) }}
      {{- ',.%s'|format((ansible_nodename|split('.'))[1:]|join('.')) }}
      {% for no_proxy in http_no_proxies %}{{- ',%s'|format(no_proxy) }}{% endfor %}
      HTTP_PROXY={{ http_proxy }}
      HTTPS_PROXY={{ https_proxy|default http_proxy }}
      FTP_PROXY={{ ftp_proxy|default http_proxy }}
      NO_PROXY=localhost,.local,.svc,127.0.0.1,::1
      {{- ',%s'|format(ansible_hostname) }}
      {{- ',.%s'|format((ansible_nodename|split('.'))[1:]|join('.')) }}
      {% for no_proxy in http_no_proxies %}{{- ',%s'|format(no_proxy) }}{% endfor %}
    path: /etc/environment
    state: present
  when:
    - http_proxy is defined
    - http_proxy|length >0
