---
# tasks file for k8s
- name: Update package cache if required
  when:
    - "'Debian' in ansible_os_family"
  ansible.builtin.apt:
    cache_valid_time: 86400
    update_cache: true

- name: Install snapd package
  ansible.builtin.package:
    name:
      - snapd
    state: present

- name: Install snapd
  community.general.snap:
    classic: true
    name:
      - snapd
    state: present

- name: Bootstrap Kubernetes
  ansible.builtin.include_tasks: "{{ k8s_type }}/main.yml"
