# https://docs.aws.amazon.com/efs/latest/ug/installing-amazon-efs-utils.html#installing-other-distro
# /etc/fstab
# fs-019b87186b4284827 /vol/efs efs x-systemd.automount,_netdev,nofail 0 0
#
- name: Pre-req.
  ansible.builtin.apt:
    name:
      - git
      - binutils

- name: Clone efs-utils
  ansible.builtin.git: # noqa: latest[git]
    accept_newhostkey: true
    dest: /usr/local/src/efs-utils
    repo: https://github.com/aws/efs-utils

- name: Build debs
  ansible.builtin.command:
    chdir: /usr/local/src/efs-utils
    cmd: ./build-deb.sh
    creates: ./build

- name: Get built packages
  ansible.builtin.find:
    paths: ['/usr/local/src/efs-utils/build']
    patterns: ['*.deb']
    recurse: false
  register: amazon_efs_utils

- name: Install efs-utils
  ansible.builtin.apt:
    deb: "{{ item.path }}"
  loop: "{{ amazon_efs_utils.files }}"

- name: Install botocore
  ansible.builtin.pip:
    name: botocore
