---
- name: Selfsigned issuer
  kubernetes.core.k8s:
    apply: true
    kubeconfig: "{{ microk8s_kubeconfig }}"
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: selfsigned
      spec:
        selfSigned: {}

- name: Selfsigned CA issuer
  kubernetes.core.k8s:
    apply: true
    kubeconfig: "{{ microk8s_kubeconfig }}"
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: selfsigned-ca
      spec:
        ca:
          secretName: selfsigned-ca-secret

- name: Selfsigned CA
  kubernetes.core.k8s:
    apply: true
    kubeconfig: "{{ microk8s_kubeconfig }}"
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: selfsigned-ca
        namespace: cert-manager
      spec:
        isCA: true
        commonName: selfsigned-ca
        secretName: selfsigned-ca-secret
        privateKey:
          algorithm: ECDSA
          size: 256
        issuerRef:
          name: selfsigned
          kind: ClusterIssuer
          group: cert-manager.io
