---
- name: Selfsigned issuer
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      cat <<EOT |microk8s kubectl apply -f -
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: selfsigned
      spec:
        selfSigned: {}
      EOT
    executable: /bin/bash
  register: selfsigned_issuer
  changed_when: "'clusterissuer.cert-manager.io/selfsigned unchanged' not in selfsigned_issuer.stdout"
  run_once: true
