- name: Hostpath storage classes ...
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      cat <<EOT | microk8s kubectl apply -f -
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: {{ item.name }}
      provisioner: microk8s.io/hostpath
      reclaimPolicy: Delete
      parameters:
        pvDir: {{ item.path }}
      volumeBindingMode: WaitForFirstConsumer
      EOT
    executable: /bin/bash
  register: microk8s_hostpath_sc_reg
  with_items: "{{ microk8s_hostpaths }}"
  changed_when: "'unchanged' not in microk8s_hostpath_sc_reg.stdout"
  run_once: true
