- name: Hostpath storage classes ...
  ansible.builtin.shell: # noqa: no-changed-when
    cmd: |
      set -o pipefail
      cat <<EOT | microk8s kubectl apply -f -
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: {{ item.name }}
      provisioner: microk8s.io/hostpath
      reclaimPolicy: Delete
      parameters:
        pvDir: {{ item.path }}
      volumeBindingMode: WaitForFirstConsumer
      EOT
    executable: /bin/bash
  with_items: "{{ microk8s_hostpaths }}"
