# roles/microk8s/tasks/ingress-lb-patch.yml
- name: Ingress service
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      cat <<EOT |microk8s kubectl apply -f -
        apiVersion: v1
        kind: Service
        metadata:
          name: ingress
          namespace: ingress
        spec:
          selector:
            name: nginx-ingress-microk8s
          type: LoadBalancer
          ports:
          - name: http
            protocol: TCP
            port: 80
            targetPort: 80
          - name: https
            protocol: TCP
            port: 443
            targetPort: 443
      EOT
    executable: /bin/bash
  register: microk8s_ingress_srv_reg
  changed_when: "'unchanged' not in microk8s_ingress_srv_reg.stdout"
  run_once: true

- name: Get nginx-ingress controller details?
  ansible.builtin.command:
    cmd: microk8s kubectl -ningress get daemonset nginx-ingress-microk8s-controller -o yaml
  changed_when: false
  register: microk8s_ingress_controller_reg

- name: Ingress IP via LB
  when:
    - "'- --publish-service=$(POD_NAMESPACE)/ingress' not in microk8s_ingress_controller_reg.stdout"
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      microk8s kubectl -ningress get daemonset nginx-ingress-microk8s-controller -o yaml \
      |sed -e 's|- --publish-status-address=.*|- --publish-service=$(POD_NAMESPACE)/ingress|' \
      |microk8s kubectl apply -f -
    executable: /bin/bash
  register: ingress_lb
  changed_when: "'unchanged' not in ingress_lb.stdout"
  run_once: true
