# roles/microk8s/tasks/ingress-lb-patch.yml
#
- name: Ingress service
  ansible.builtin.shell: # noqa: no-changed-when
    cmd: |
      set -o pipefail
      cat <<EOT |microk8s kubectl apply -f -
        apiVersion: v1
        kind: Service
        metadata:
          name: ingress
          namespace: ingress
        spec:
          selector:
            name: nginx-ingress-microk8s
          type: LoadBalancer
          ports:
          - name: http
            protocol: TCP
            port: 80
            targetPort: 80
          - name: https
            protocol: TCP
            port: 443
            targetPort: 443
      EOT
    executable: /bin/bash

- name: Ingress IP via LB
  ansible.builtin.shell: # noqa: no-changed-when
    cmd: |
      set -o pipefail
      microk8s kubectl -ningress get daemonset nginx-ingress-microk8s-controller -o yaml \
      |sed -e 's|- --publish-status-address=.*|- --publish-service=$(POD_NAMESPACE)/ingress|' \
      |microk8s kubectl apply -f -
    executable: /bin/bash
