---
# handlers file for microk8s
- name: Create tmpfiles
  ansible.builtin.command: # noqa: no-changed-when
    cmd: systemd-tmpfiles --create

- name: Restart microk8s
  ansible.builtin.command: # noqa: no-changed-when
    cmd: snap restart microk8s
