---
# handlers file for microk8s
- name: create tmpfiles
  ansible.builtin.command:
    cmd: systemd-tmpfiles --create

- name: restart microk8s
  ansible.builtin.command:
    cmd: snap restart microk8s
