# collection/roles/k8sclient/tasks/epel/main.yml
- name: Has subscription-manager?
  ansible.builtin.command:
    cmd: which subscription-manager
  register: subscription_manager_reg
  changed_when: false

- name: Set facts
  ansible.builtin.set_fact:
    dnf_cm_set_enabled: "{{ 'crb' if ansible_distribution_version < 8 else 'powertools' }}"
    sm_repos_enable: codeready-builder-for-rhel-{{ ansible_distribution_version }}-{{ ansible_architecture }}-rpms

- name: Enable codeready-builder-for-rhel
  when: subscription_manager_reg.rc == 0
  ansible.builtin.shell:
    cmd: |
      subscription-manager repos --enable {{ sm_repos_enable }}
  register: subscription_manager_reg
  changed_when: true

- name: Enable pre-req. repo
  when: subscription_manager_reg.rc != 0
  ansible.builtin.shell:
    cmd: |
      dnf config-manager --set-enabled {{ dnf_cm_set_enabled }}
  register: config_manager_reg
  changed_when: true

- name: Install EPEL release
  ansible.builtin.dnf:
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_version }}.noarch.rpm
    state: present
    update_cache: true
