---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bind9
data:
  named.conf.options: |
    include "/etc/bind/rndc.key";
    controls { inet 127.0.0.1 port 5953 allow { 127.0.0.1; } keys { "rndc-key"; }; };
    options {
      directory "/var/cache/bind";
      dnssec-validation no;
      #dnssec-validation auto;
      listen-on-v6 { any; };
      forwarders { 10.0.0.2; };
      forward only;
      allow-query { any; };
      #allow-query { 127.0.0.1; ::1; 10/8; 172.16/12; 192.168/16; fe80::/10; };
    };
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bind9-zone
data:
  db.fake.sydney.edu.au: |
    $TTL 60
    $ORIGIN fake.sydney.edu.au.
    @ IN SOA fake.sydney.edu.au. root.ip-10-0-19-23.ap-southeast-2.compute.internal. (1 60 60 60 60);
    @ IN NS ip-10-0-19-23.ap-southeast-2.compute.internal.
