---
# defaults file for desktop
desktop_apptainer_enabled: true
desktop_apptainer_cachedir: ""
desktop_apptainer_tmpdir: ""
desktop_apptainer_version: "latest"

# http://conky.sourceforge.net/config_settings.html
# http://conky.sourceforge.net/variables.html
desktop_conky_enabled: true
desktop_conky_default_interface: "{{ ansible_default_ipv4.interface }}"
desktop_conky_alignment: top_right
desktop_conky_config_extra: ""
desktop_conky_default_color: white
desktop_conky_default_outline_color: white
desktop_conky_default_shade_color: white
desktop_conky_double_buffer: true
desktop_conky_own_window_argb_visual: true
desktop_conky_own_window_hints: undecorated,below,sticky,skip_taskbar,skip_pager
desktop_conky_own_window_transparent: true
desktop_conky_own_window_type: normal
desktop_conky_update_interval: 5.0
desktop_conky_file_systems: []
# - /scratch
desktop_conky_text_extra: ""

# On startup, dconf consults the DCONF_PROFILE environment variable.
desktop_dconf_profile: ""

# Settings for any Gnome based desktop, includes Mate
desktop_gnome_nfs_user_home: false
# gsettings list-schemas --print-paths
desktop_gnome_settings:
  org/mate/desktop/lockdown:
    disable-user-switching: false
  org/mate/screensaver:
    idle-activation-enabled: true
    user-switch-enabled: true
# Additional dconf database locks
# Settings in `desktop_gnome_settings` are automatically locked
desktop_gnome_setting_locks: []

# TODO not yet configured
desktop_mfa_enabled: false

# TODO not yet fully tested, options not implemented
# https://github.com/aws/efs-utils/tree/v1.36.0?tab=readme-ov-file#enable-mount-successfailure-notification-via-cloudwatch-log
desktop_amazon_efs_utils_enabled: false
desktop_amazon_efs_utils_version: "1.36.0"
desktop_amazon_efs_utils_cloudwatch_enabled: false
desktop_amazon_efs_utils_optimized_readahead: true
desktop_amazon_efs_utils_fall_back_to_mount_target_ip_address: true
desktop_amazon_efs_utils_imdsv2: true
# https://github.com/aws/efs-utils/tree/v1.36.0?tab=readme-ov-file#use-assumerolewithwebidentity
desktop_amazon_efs_utils_aws_web_identity_token_file: ""
desktop_amazon_efs_utils_role_arn: ""
desktop_amazon_efs_utils_fips_mode: false

# Amazon DCV remote desktop and application streaming
desktop_nice_dcv_enabled: false
desktop_nice_dcv_version: 2024.0-18131

desktop_patching_enabled: true

desktop_rdp_enabled: false

desktop_target_default: graphical.target

# TODO not yet configured
desktop_turbovnc_enabled: false

desktop_virtualgl_enabled: false
desktop_virtualgl_version: latest

# https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
# Additional paths for XDG configurations
desktop_xdg_config_dirs: []
desktop_xdg_data_dirs: []
