---
# defaults file for microk8s
## \param microk8s_enable []string addons to enable `microk8s status` lists available options.
microk8s_enable: []
## \param microk8s_addons []string addons to enable `microk8s status` lists available options.
microk8s_addons: []

microk8s_cni_ipv4_enabled: true
microk8s_cni_ipv4_cluster_cidr: 10.1.0.0/16
microk8s_cni_ipv4_service_cidr: 10.152.183.0/24
microk8s_cni_ipv6_enabled: false
microk8s_cni_ipv6_cluster_cidr: fdf4:8ab3:60fb::/64
microk8s_cni_ipv6_service_cidr: fdf4:8ab3:60fb:fffe::/108

microk8s_dexidp_enabled: false
microk8s_dexidp_port: 31000

microk8s_oidc_ca_file: "${SNAP_DATA}/certs/dex-ca.crt"
microk8s_oidc_issuer: "https://{{ ansible_default_ipv4.address }}:{{ microk8s_dexidp_port }}/dex"
microk8s_oidc_username_claim: name
microk8s_oidc_username_prefix: "dex:"

## \param microk8s_calicoctl_version string calicoctl version to install on host.
microk8s_calicoctl_version: ""
# microk8s_calicoctl_version: v3.25.1

## \param microk8s_storageclass_default string not currently used
microk8s_storageclass_default: ""

microk8s_users: []

## \param microk8s_wireguard_enabled boolean Calico host2host in transit encryption requirement
microk8s_wireguard_enabled: false

# https://microk8s.io/docs/addon-hostpath-storage
## \param microk8s_hostpaths []object Storage class dynamic provisioning local directory paths
## \param microk8s_hostpaths.[].name string Storage class name
## \param microk8s_hostpaths.[].path string Host directory base path
microk8s_hostpaths: []
# - name: scratch-hostpath
#   path: /scratch/{{ ansible_machine_id }}/microk8s-hostpath
# - name: ssd-hostpath
#   path: /ssd/microk8s-hostpath

## \param microk8s_local_storage []object Persistent volume(s) for local host directory path
## \param microk8s_local_storage.[].path string Host directory path
## \param microk8s_local_storage.[].age string Directory cleanup time period
## \param microk8s_local_storage.[].claimRef object
##   [Reserving a PersistentVolume](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reserving-a-persistentvolume)
microk8s_local_storage: []
# - path: /scratch/cryosparc
#   age: 1w

## \param microk8s_metallb_range string Load balancer IP address ranges
microk8s_metallb_range: "{{ ansible_default_ipv4.network + '/' + ansible_default_ipv4.prefix }}"
microk8s_metallb_address_pool: ["10.152.184.0/24"]
# https://prometheus.io/docs/guides/node-exporter/
microk8s_node_exporter_metrics_enabled: false
