---
# defaults file for microk8s
microk8s_enable: [cert-manger,dns,ha-cluster,helm3,ingress,metallb,rbac,registry]
microk8s_metallb_range: "{{ ansible_default_ipv4.network+'/'+ansible_default_ipv4.prefix }}"
# local-storage mount paths
microk8s_local_storage: []
# - path: /scratch/cryosparc
#   age: 1w
# https://prometheus.io/docs/guides/node-exporter/
microk8s_node_exporter_metrics_enabled: false
