---
# tasks file for named
- name: Install bind9
  ansible.builtin.apt:
    cache_valid_time: 86400
    name:
      - bind9
    state: present
    update_cache: true

- name: Get upstream dns server(s)
  ansible.builtin.shell: # noqa: no-changed-when
    cmd: |
      set -o pipefail
      resolvectl -i{{ ansible_default_ipv4.interface }} dns \
      |sed 's/.*:\s\+\([0-9a-f.: ]*\).*$/\1/'
    executable: /bin/bash
  register: bind_forwarders

- name: Zones
  ansible.builtin.include_tasks: configure_zone.yml
  vars:
    dns_zone: "{{ item }}"
  loop: "{{ named_zones | flatten(levels=1) }}"

- name: Configure named.conf.options
  ansible.builtin.template:
    backup: true
    dest: /etc/bind/named.conf.options
    lstrip_blocks: true
    src: named.conf.options.j2
    mode: "0644"
    # validate: ???
  notify:
    - Reload named

- name: Include named.conf.ansible
  ansible.builtin.lineinfile:
    insertafter: include "/etc/bind/named.conf.options";
    line: include "/etc/bind/named.conf.ansible";
    path: /etc/bind/named.conf
  notify:
    - Reload named

- name: Enable named.service
  ansible.builtin.service:
    name: named.service
    state: started
