---
# tasks file for docker
- name: Update package cache if required
  when: "'Debian' in ansible_os_family"
  ansible.builtin.apt:
    cache_valid_time: 86400
    update_cache: true

- name: Uninstall old versions
  ansible.builtin.package:
    name:
      - containerd
      - docker.io
      - docker-compose
      - docker-compose-v2
      - docker-doc
      - podman-docker
      - runc
    state: absent

- name: Set facts
  ansible.builtin.set_fact:
    docker_architecture: >-
      {{ ansible_architecture |
      replace('x86_64', 'amd64') |
      replace('aarch64', 'arm64') }}

- name: Install GPG signing key
  ansible.builtin.get_url:
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Configure repository
  ansible.builtin.apt_repository:
    filename: docker
    repo: >-
      deb
      [arch={{ docker_architecture }} signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }}
      stable
    state: present
    update_cache: true

# Require Apt. Package timing issue with update_cache operation.
# ISSUE. No package matching 'docker-ce' is available
- name: Install
  ansible.builtin.apt:
    cache_valid_time: 0
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Add users to docker group
  ansible.builtin.user:
    append: true
    groups: [docker]
    name: "{{ item }}"
  with_items: "{{ docker_users }}"

- name: Configure daemon
  ansible.builtin.copy:
    content: |
      {
        "insecure-registries": {{ docker_insecure_registeries | to_json }}
      }
    dest: /etc/docker/daemon.json
    mode: "0644"
  notify:
    - Restart docker

- name: Enable docker service
  ansible.builtin.service:
    enabled: true
    name: docker
    state: started
