---
- name: OS update, reboot if required
  hosts: "{{ target|default('all') }}" # noqa: internal-error
  become: true

  tasks:
    - name: Update OS
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Reboot required?
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot required
      ansible.builtin.reboot:
      when:
        - reboot_required_file.stat.exists
