---
# playbooks/aws-vrd-dev-lab.yaml
# ansible-playbook aws-vrd-dev-lab.yaml -e "{subnet_id: subnet-02d6a89d6f0aee6a8, vpc_id: vpc-0a254c860b07b760a}"
# NB: AWS_PROFILE environment variable required if not default target account
#
- name: AWS virtual research desktop development lab
  hosts: localhost
  connection: local
  vars:
    default_keyname: dean.taylor@sydney.edu.au
    default_uuid: v1-0-0
    # default_uuid: ccf512e294dd
    tags_template:
      sydney.edu.au/resTek/ansiblePlaybook: amazon-vrd-dev-lab.yaml

  pre_tasks: []

  tasks:
    - name: Get AMIs
      amazon.aws.ec2_ami_info:
        filters:
          name: ubuntu-jammy-22.04-amd64-server-cvl-desktop-*
        owners: ["381427642830"]
      register: amis

    - name: Get subnet
      amazon.aws.ec2_vpc_subnet_info:
        filters:
          state: available
          # map_public_ip_on_launch: true
      register: subnets

    - name: Facts
      ansible.builtin.set_fact:
        default_ami: "{{ amis.images | last }}"
        default_subnet: "{{ subnets.subnets|selectattr('map_public_ip_on_launch','equalto',true)|sort(attribute='available_ip_address_count')|last }}"

    - name: Default AMI
      ansible.builtin.debug:
        var: default_ami
    - name: Default subnet
      ansible.builtin.debug:
        var: default_subnet

    - name: Get launch template
      ansible.builtin.uri:
        return_content: true
        url: https://raw.githubusercontent.com/SydneyResearchTech/cfn-templates/main/vrd-launch-template.cfn.yml
      register: cfn_vrd_launch_template

    - name: Generate password
      ansible.builtin.set_fact:
        password: "{{ lookup('ansible.builtin.password', '/dev/null', seed=inventory_hostname) }}"

    - name: Cloudformation launch template
      amazon.aws.cloudformation:
        capabilities: ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
        # disable_rollback: false
        on_create_failure: DELETE
        profile: public
        stack_name: "{{ 'restek-vrd-launch-template-' ~ (uuid|default(default_uuid)) }}"
        state: "{{ state | default('present') }}"
        tags: "{{ tags_template }}"
        template_body: "{{ cfn_vrd_launch_template.content }}"
        # template_body: "{{ lookup('ansible.builtin.file', '/Users/dean/cfn-templates/vrd-launch-template.cfn.yml') }}"
        template_parameters:
          ImageId: "{{ amis.images[-1].image_id }}"
          InstanceType: g4dn.xlarge
          KeyName: "{{ keyname | default(default_keyname) }}"
          SubnetId: "{{ subnet_id | default(default_subnet.subnet_id) }}"
          VpcId: "{{ vpc_id | default(default_subnet.vpc_id) }}"
      when:
        - cfn_vrd_launch_template.status == 200
        - 0 > 1

    - name: Get vrd-dev.cfn.yml
      ansible.builtin.uri:
        return_content: true
        url: https://raw.githubusercontent.com/SydneyResearchTech/cfn-templates/main/vrd-lab.cfn.yml
      register: cfn_vrd_dev

    - name: Deploy VRD environment
      amazon.aws.cloudformation:
        capabilities: ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
        # disable_rollback: false
        on_create_failure: DELETE
        profile: public
        stack_name: "{{ 'restek-vrd-lab-' ~ (uuid|default(default_uuid)) }}"
        state: "{{ state | default('present') }}"
        tags: "{{ tags_template }}"
        template_body: "{{ cfn_vrd_launch_template.content }}"
        # template_body: "{{ lookup('ansible.builtin.file', '/Users/dean/cfn-templates/vrd-lab.cfn.yml') }}"
        template_parameters:
          AvailabilityZones: ap-southeast-2a
          # AvailabilityZones: "{{ availability_zone | default(default_subnet.availability_zone) }}"
          ASGDesiredCapacity: "{{ capacity | default(1) }}"
          LaunchTemplateName: "{{ 'restek-vrd-launch-template-' ~ (uuid|default(default_uuid)) }}"
          LaunchTemplateVersion: 1
      when:
        - cfn_vrd_launch_template.status == 200
