---
# restek.core.eks_create_cluster collection playbook
# ansible-playbook -e 'cluster_name=restek-dev' restek.core.eks_create_cluster
# python3 -m pip install kubernetes
#
- name: AWS EKS create cluster
  hosts: localhost
  become: false
  connection: local
  vars:
    addons:
      - aws-ebs-csi-driver
      - aws-efs-csi-driver
      - snapshot-controller
      # - aws-mountpoint-s3-csi-driver
      # - amazon-cloudwatch-observability
    aws_profile: default
    calico_enabled: false
    calico_ipv4pool_cidr: "172.16.0.0/16"
    calico_ipv6pool_cidr: "fd10:28d:94c::/48"
    calico_version: "3.29.1"
    clobber: false
    cluster_name: ""
    eksctl_create: false
    flux_dir: "{{ (lookup('ansible.builtin.env', 'HOME'), 'flux') | path_join }}"
    ipv6: true
    karpenter_namespace: kube-system
    karpenter_version: "1.1.1"
    kubernetes_version: "1.31"
    vpc_cidr: "192.168.0.0/16"
    vpc_id: ""

  pre_tasks:
    - name: Mandatory variables?
      ansible.builtin.assert:
        that:
          - cluster_name is regex("^[a-z0-9][a-z0-9-]+")

    - name: Flux directory exists?
      ansible.builtin.stat:
        path: "{{ flux_dir }}"
      register: flux_dir_stat
    - name: Fail if flux directory does not exist
      when:
        - not flux_dir_stat.stat.exists
      ansible.builtin.fail:
        msg: |
          Run git clone git@github.com:SydneyResearchTech/gitops-flux.git {{ flux_dir }}
          OR provide the flux_dir parameter with the correct path

  roles: []

  tasks:
    - name: Get AWS region
      ansible.builtin.command:
        cmd: aws configure get region --profile {{ aws_profile }}
      changed_when: false
      register: region_output

    - name: Get AWS account ID
      ansible.builtin.command:
        cmd: aws sts get-caller-identity --profile {{ aws_profile }} --output text --query 'Account'
      changed_when: false
      register: aws_account_id_output
    # - ansible.builtin.debug: {var: aws_account_id_output}

    - name: AWS KMS create key
      amazon.aws.kms_key:
        alias: eks-secrets-{{ cluster_name }}
        description: EKS secrets encryption for cluster {{ cluster_name }}
        key_spec: SYMMETRIC_DEFAULT
        key_usage: ENCRYPT_DECRYPT
        profile: "{{ aws_profile }}"
        state: present
        tags:
          alpha.eksctl.io/cluster-name: "{{ cluster_name }}"
          eksctl.cluster.k8s.io/v1alpha1/cluster-name: "{{ cluster_name }}"
          sydney.edu.au/ou: Research Technology
          sydney.edu.au/resTek/contact: ais.admin@sydney.edu.au
      register: kms_key_output
    # - ansible.builtin.debug: {var: kms_key_output}

    - name: Set facts
      ansible.builtin.set_fact:
        account_id: "{{ aws_account_id_output.stdout }}"
        # flux_dir: "{{ (lookup('ansible.builtin.env', 'HOME'), 'flux') | path_join }}"
        key_arn: "{{ kms_key_output.key_arn }}"
        region: "{{ region_output.stdout }}"

    # https://karpenter.sh/v0.37/getting-started/getting-started-with-karpenter/
    - name: Get karpenter provider cfn
      ansible.builtin.uri:
        force: true
        return_content: true
        url: "https://raw.githubusercontent.com/aws/karpenter-provider-aws\
              /v{{ karpenter_version }}\
              /website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml"
      register: karpenter_cfn_output

    - name: Karpenter cloudformation deploy
      amazon.aws.cloudformation:
        capabilities: ["CAPABILITY_NAMED_IAM"]
        on_create_failure: DELETE
        profile: "{{ aws_profile }}"
        stack_name: Karpenter-{{ cluster_name }}
        state: present
        tags:
          alpha.eksctl.io/cluster-name: "{{ cluster_name }}"
          eksctl.cluster.k8s.io/v1alpha1/cluster-name: "{{ cluster_name }}"
          sydney.edu.au/ou: Research Technology
          sydney.edu.au/resTek/createBy: dean.taylor@sydney.edu.au
        template_body: "{{ karpenter_cfn_output.content }}"
        template_parameters:
          ClusterName: "{{ cluster_name }}"
      when:
        - karpenter_cfn_output.status == 200

    # - name: Clone flux repository
    #   ansible.builtin.git:
    #     clone: true
    #     dest: "{{ flux_dir }}"
    #     repo: "git@github.com:SydneyResearchTech/gitops-flux.git"
    #     update: true

    - name: Create EKS cluster bootstrap for Calico CNI
      when:
        - calico_enabled
      ansible.builtin.template:
        backup: true
        dest: "{{ flux_dir }}/clusters/{{ cluster_name }}-bootstrap.eks.yaml"
        lstrip_blocks: true
        mode: "0644"
        src: template.eks.yaml.j2
      vars:
        bootstrap: true

    - name: Create EKS cluster template file
      ansible.builtin.template:
        backup: true
        dest: "{{ flux_dir }}/clusters/{{ cluster_name }}.eks.yaml"
        lstrip_blocks: true
        mode: "0644"
        src: template.eks.yaml.j2
      vars:
        bootstrap: false

    - name: Get EKS Cluster Security Group
      amazon.aws.ec2_security_group_info:
        profile: "{{ aws_profile }}"
        filters: "{{ filters_95e36919 | items2dict }}"
      vars:
        filters_95e36919:
          - key: group-name
            value: "eks-cluster-sg-{{ cluster_name }}-*"
          - key: "tag:aws:eks:cluster-name"
            value: "{{ cluster_name }}"
          - key: "tag:kubernetes.io/cluster/{{ cluster_name }}"
            value: owned
      register: cluster_sg_output
    # - ansible.builtin.debug: {var: cluster_sg_output }

    - name: Get EKS cluster subnets
      amazon.aws.ec2_vpc_subnet_info:
        filters:
          "tag:eksctl.cluster.k8s.io/v1alpha1/cluster-name": "{{ cluster_name }}"
          "tag:kubernetes.io/role/elb": 1
        profile: "{{ aws_profile }}"
      register: cluster_sn_output
    # - ansible.builtin.debug: {var: cluster_sn_output}

    - name: Post EKS cluster creation
      when:
        - cluster_sg_output.security_groups | length > 0
        - cluster_sn_output.subnets | length > 0
      block:
        - name: Get kubectl config
          ansible.builtin.command:
            cmd: >
              aws eks update-kubeconfig --name {{ cluster_name }}
              --profile {{ aws_profile }}
              --kubeconfig /dev/null --dry-run
          register: kubeconfig_output
          changed_when: false

        - name: Set Facts
          ansible.builtin.set_fact:
            kubeconfig: "{{ kubeconfig_output.stdout | from_yaml }}"

        - name: Calico installation
          when:
            - calico_enabled
          block:
            - name: K8s cluster info
              kubernetes.core.k8s_cluster_info:
                kubeconfig: "{{ kubeconfig }}"
              register: k8s_cluster_info_output

            # https://docs.tigera.io/calico/latest/getting-started/kubernetes/managed-public-cloud/eks
            - name: Calico operator installation
              when:
                - k8s_cluster_info_output['apis']['operator.tigera.io/v1'] is undefined
              kubernetes.core.k8s:
                apply: false
                kubeconfig: "{{ kubeconfig }}"
                src: https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/tigera-operator.yaml
                state: present

            - name: Calico installation
              kubernetes.core.k8s:
                apply: true
                kubeconfig: "{{ kubeconfig }}"
                template: "k8s/calico-installation.yaml.j2"

            - name: Create nodegroups
              ansible.builtin.command:
                cmd: eksctl create nodegroup -f {{ flux_dir }}/clusters/{{ cluster_name }}.eks.yaml
              changed_when: true

            - name: Calico status?
              kubernetes.core.k8s_info:
                field_selectors:
                  - status.phase!=Running
                kind: Pod
                kubeconfig: "{{ kubeconfig }}"
                namespace: calico-system
              register: calico_system
              delay: 10
              retries: 12
              until: calico_system.resources | length <= 0
            # - ansible.builtin.debug: {var: calico_system}
            # - ansible.builtin.fail: {msg: testing calico}

            - name: Create Fargate profile
              ansible.builtin.command:
                cmd: eksctl create fargateprofile -f {{ flux_dir }}/clusters/{{ cluster_name }}.eks.yaml
              changed_when: true

            - name: Create IAM service accounts
              ansible.builtin.command:
                cmd: >-
                  eksctl create iamserviceaccount
                  -f {{ flux_dir }}/clusters/{{ cluster_name }}.eks.yaml
                  --approve
              changed_when: true

            - name: Get cfn podidentityrole-kube-system-karpenter
              amazon.aws.cloudformation_info:
                profile: "{{ aws_profile }}"
                stack_name: eksctl-{{ cluster_name }}-podidentityrole-kube-system-karpenter
              ignore_errors: true
              register: cfn_podidentityrole
            # - ansible.builtin.debug: {var: cfn_podidentityrole}

            - name: Create Pod Identity associations
              when:
                - cfn_podidentityrole.failed
              ansible.builtin.command:
                cmd: eksctl create podidentityassociation -f {{ flux_dir }}/clusters/{{ cluster_name }}.eks.yaml
              changed_when: true

            - name: WORKAROUND add LB firewall rules
              when:
                - 0 > 1
              amazon.aws.ec2_security_group:
                profile: "{{ aws_profile }}"
                description: "{{ cluster_sg_output.security_groups.0.description }}"
                name: "{{ cluster_sg_output.security_groups.0.group_name }}"
                group_id: "{{ cluster_sg_output.security_groups.0.group_id }}"
                purge_rules: false
                rules:
                  - cidr_ip: "{{ vpc_cidr }}"
                    ports:
                      - 30000-32767
                    proto: tcp
                    rule_desc: ANSIBLE WORKAROUND ISSUE LB controller
                  - cidr_ip: "{{ vpc_cidr }}"
                    ports:
                      - 30000-32767
                    proto: udp
                    rule_desc: ANSIBLE WORKAROUND ISSUE LB controller
                state: present


            - name: Enable FluxCD
              ansible.builtin.command:
                cmd: eksctl enable flux -f {{ flux_dir }}/clusters/{{ cluster_name }}.eks.yaml
              changed_when: true

        - name: Flux directories
          ansible.builtin.file:
            mode: "0755"
            path: "{{ flux_dir }}/{{ item }}"
            state: directory
          with_items:
            - infrastructure/overlays
            - infrastructure/overlays/{{ cluster_name }}
            - infrastructure/overlays/{{ cluster_name }}/controller
            - infrastructure/overlays/{{ cluster_name }}/config
            - apps/overlays/{{ cluster_name }}

        - name: Secret encryption?
          ansible.builtin.stat:
            path: "{{ flux_dir }}/infrastructure/{{ cluster_name }}/.sops.yaml"
          register: sops_output

        - name: Secret configuration
          when:
            - not sops_output.stat.exists
          block:
            - name: Generate age key
              ansible.builtin.command:
                cmd: age-keygen
              register: agekey_output
              changed_when: false

            - name: Age secret
              kubernetes.core.k8s:
                apply: true
                kubeconfig: "{{ kubeconfig }}"
                resource_definition:
                  apiVersion: v1
                  kind: Secret
                  metadata:
                    name: sops-age
                    namespace: flux-system
                  data:
                    age.agekey: "{{ agekey_output.stdout | b64encode }}"
                state: present

            - name: Set Facts
              ansible.builtin.set_fact:
                agekey_public: >-
                  {{ agekey_output.stdout |
                  regex_search('public key: (.*)$', '\\1', multiline=True) | first }}

            - name: SOPS configuration
              ansible.builtin.copy:
                content: |
                  creation_rules:
                  - path_regex: .*.ya?ml
                    encrypted_regex: '^(data|stringData)$'
                    age: >-
                      {{ agekey_public }}
                dest: "{{ flux_dir }}/{{ item }}"
                mode: "0644"
              with_items:
                - infrastructure/{{ cluster_name }}/.sops.yaml
                - apps/{{ cluster_name }}/.sops.yaml

        - name: Get EFS cfn
          ansible.builtin.uri:
            return_content: true
            url: https://raw.githubusercontent.com/SydneyResearchTech/cfn-templates/main/efs.cfn.yml
          register: efs_cfn_output

        - name: EFS deployment
          when:
            - efs_cfn_output.status == 200
          amazon.aws.cloudformation:
            on_create_failure: DELETE
            profile: "{{ aws_profile }}"
            stack_name: eks-{{ cluster_name }}-efs-csi
            state: present
            tags:
              alpha.eksctl.io/cluster-name: "{{ cluster_name }}"
              eksctl.cluster.k8s.io/v1alpha1/cluster-name: "{{ cluster_name }}"
              sydney.edu.au/ou: Research Technology
              sydney.edu.au/resTek/createBy: dean.taylor@sydney.edu.au
            template_body: "{{ efs_cfn_output.content }}"
            template_parameters:
              VpcId: "{{ cluster_sg_output.security_groups.0.vpc_id }}"
              SecurityGroupId: "{{ cluster_sg_output.security_groups.0.group_id }}"
              SubnetId1: "{{ cluster_sn_output.subnets.0.id }}"
              SubnetId2: "{{ cluster_sn_output.subnets.1.id }}"
              SubnetId3: "{{ cluster_sn_output.subnets.2.id }}"
          register: efs_output
        # - ansible.builtin.debug: {var: efs_output}

        - name: Set Facts
          ansible.builtin.set_fact:
            efs_file_system_id: "{{ efs_output.stack_outputs.FileSystemId }}"

        - name: Flux cluster secrets
          when:
            - 0 > 1
          ansible.builtin.template:
            backup: true
            dest: "{{ flux_dir }}/clusters/{{ cluster_name }}/secrets.yaml"
            force: "{{ clobber }}"
            lstrip_blocks: true
            mode: "0644"
            src: flux/clusters/secrets.yaml.j2

        - name: Flux cluster infrastructure
          ansible.builtin.template:
            backup: true
            dest: "{{ flux_dir }}/clusters/{{ cluster_name }}/infrastructure.yaml"
            force: "{{ clobber }}"
            lstrip_blocks: true
            mode: "0644"
            src: flux/clusters/infrastructure.yaml.j2

        - name: Flux cluster applications
          when:
            - 0 > 1
          ansible.builtin.template:
            backup: true
            dest: "{{ flux_dir }}/clusters/{{ cluster_name }}/apps.yaml"
            force: "{{ clobber }}"
            lstrip_blocks: true
            mode: "0644"
            src: flux/clusters/apps.yaml.j2

        - name: Flux cluster notifications
          when:
            - 0 > 1
          ansible.builtin.template:
            backup: true
            dest: "{{ flux_dir }}/clusters/{{ cluster_name }}/notification.yaml"
            force: "{{ clobber }}"
            lstrip_blocks: true
            mode: "0644"
            src: flux/clusters/notification.yaml.j2

  post_tasks: []
  handlers: []
