---
# https://ubuntu.com/server/docs/nvidia-drivers-installation
# https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
- name: NVIDIA drivers and CUDA toolkit
  hosts: "{{ target|default('all') }}"
  become: true

  tasks:
    - name: NVIDIA recommended driver?
      ansible.builtin.command:
        cmd: ubuntu-drivers list --gpgpu --recommended
      changed_when: false
      register: nvidia_driver_recommend
    # - ansible.builtin.debug: {var: nvidia_driver_recommend}

    - name: Facts
      ansible.builtin.set_fact:
        distro: "{{ [(ansible_distribution | lower), (ansible_distribution_version | split('.') | join())] | join() }}"
        arch: "{{ ansible_architecture }}"
        nvidia_driver_branch: "{{ (nvidia_driver_recommend.stdout_lines.0).split('-').2 }}"

    - name: NVIDIA driver package exists?
      ansible.builtin.shell:
        cmd: >
          set -o pipefail;
          apt-cache policy nvidia-dkms-{{ nvidia_driver_branch }}-server |
          grep -v nvidia-dkms-{{ nvidia_driver_branch }}-server
        executable: /bin/bash
      changed_when: false

    - name: Remove previous CUDA toolkit
      ansible.builtin.command:
        cmd: /usr/local/cuda-11.7/bin/cuda-uninstaller --silent
        removes: /usr/local/cuda-11.7/bin/cuda-uninstaller

    - name: Remove manually installed nvidia drivers
      ansible.builtin.command:
        cmd: /usr/bin/nvidia-uninstall
        removes: /usr/bin/nvidia-uninstall

    - name: Install NVIDIA packages pre-req
      ansible.builtin.apt:
        cache_valid_time: 86400
        name:
          - linux-headers-{{ ansible_kernel }}
        state: present
        update_cache: true

    - name: Install NVIDIA driver
      ansible.builtin.package:
        name:
          - nvidia-dkms-{{ nvidia_driver_branch }}-server
          - nvidia-driver-{{ nvidia_driver_branch }}-server
          - nvidia-utils-{{ nvidia_driver_branch }}-server
          - nvidia-fabricmanager-{{ nvidia_driver_branch }}
          - libnvidia-nscq-{{ nvidia_driver_branch }}
      notify:
        - Reboot

    # sudo apt-key del 7fa2af80
    - name: Deleted old NVIDIA repo Apt key
      ansible.builtin.apt_key:
        id: "7fa2af80"
        state: absent

    - name: Install new cuda-keyring
      ansible.builtin.apt:
        deb: https://developer.download.nvidia.com/compute/cuda/repos/{{ distro }}/{{ arch }}/cuda-keyring_1.1-1_all.deb
        state: present

    - name: Add CUDA repo
      ansible.builtin.apt_repository:
        filename: cuda-{{ distro }}-{{ arch }}
        mode: "0644"
        repo: >
          deb [signed-by=/usr/share/keyrings/cuda-archive-keyring.gpg]
          https://developer.download.nvidia.com/compute/cuda/repos/{{ distro }}/{{ arch }}/ /
        state: present
        update_cache: true

    - name: Add pin file to prioritize CUDA repo
      ansible.builtin.get_url:
        dest: /etc/apt/preferences.d/cuda-repository-pin-600
        mode: "0644"
        url: https://developer.download.nvidia.com/compute/cuda/repos/{{ distro }}/{{ arch }}/cuda-{{ distro }}.pin

    - name: Install CUDA toolkit
      ansible.builtin.apt:
        cache_valid_time: 86400
        name:
          - cuda-toolkit
          - nvidia-gds
        state: present
        update_cache: true
      notify:
        - Reboot

  handlers:
    - name: Reboot
      ansible.builtin.reboot:
