---
# https://ubuntu.com/server/docs/nvidia-drivers-installation
# https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
- name: NVIDIA drivers and CUDA toolkit
  hosts: "{{ target|default('all') }}"
  become: true

  pre_tasks:
    - name: Remove previous CUDA toolkit
      ansible.builtin.command:
        cmd: /usr/local/cuda-11.7/bin/cuda-uninstaller --silent
        removes: /usr/local/cuda-11.7/bin/cuda-uninstaller

  roles:
    - role: restek.core.nvidia
