- name: Linux Virtual Desktop
  hosts: "{{ target|default('all') }}"
  become: true
  vars:
    vdi_default_target: multi-user.target
    vdi_ssh_known_hosts: []
    vdi_sync: true
    vdi_virtualgl_version: "latest"

  pre_tasks:
    - name: Ansible facts
      ansible.builtin.file:
        mode: "0755"
        path: "{{ item }}"
        state: directory
      with_items:
        - /etc/ansible
        - /etc/ansible/facts.d

    - name: PCI facts
      ansible.builtin.copy:
        dest: /etc/ansible/facts.d/pci_slots.fact
        mode: "755"
        src: ansible/facts.d/lspci2json.py
      register: lspci2json_py

    - name: Reload facts # noqa: no-handler
      when: lspci2json_py.changed
      ansible.builtin.setup:
        filter: ansible_local

    - name: Add ssh known hosts
      ansible.builtin.known_hosts:
        hash_host: true
        key: "{{ item.key }}"
        name: "{{ item.name }}"
        path: /etc/ssh/ssh_known_hosts
        state: present
      with_items: "{{ vdi_ssh_known_hosts }}"

  roles:
    - role: restek.core.apptainer
    - role: restek.core.docker
      docker_insecure_registeries: [localhost:32000]
      docker_users: [ubuntu]
    - role: restek.core.microk8s
      microk8s_users: [ubuntu]
    - role: restek.core.desktop
      desktop_apptainer_enabled: true
      desktop_conky_enabled: true
      desktop_target_default: multi-user.target
      desktop_virtualgl_enabled: true

  tasks:
    - name: Sync configuration
      when: vdi_sync
      block:
        - name: Install systemd timer
          ansible.builtin.copy:
            dest: /etc/systemd
            directory_mode: "0755"
            mode: preserve
            src: systemd
          notify:
            - Reload systemd
            - Restart virtual_desktop timer
          register: timer_reg

        - name: Reload systemd # noqa no-handler
          when: timer_reg.changed
          ansible.builtin.systemd:
            daemon_reload: true

        - name: Start virtual desktop timer
          ansible.builtin.service:
            enabled: true
            name: virtual_desktop.timer
            state: started

  post_tasks:
    - name: Uninstall mate-power-manager
      ansible.builtin.package:
        name: mate-power-manager
        state: absent

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Restart virtual_desktop timer
      ansible.builtin.service:
        name: virtual_desktop.timer
        state: restart
