---
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: "-v"
          setup_python: "true"
          requirements_file: requirements.txt
